version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      remix:
        patterns:
          - '@remix-run/**'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/coverage-v8'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
