version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      react-router:
        patterns:
          - '@react-router/**'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/coverage-v8'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
