version: '3'

tasks:
  dev:
    deps: [dev:client]
  dev:client:
    dir: packages/client
    cmds:
      - pnpm dev

  start:supabase:
    dir: packages/supabase
    status:
      - pnpm status
    cmds:
      - pnpm start

  sst:dev:
    dir: packages/client
    cmds:
      - pnpm sst:dev

  build:
    deps: [build:client]
  build:client:
    dir: packages/client
    cmds:
      - pnpm build

  start:
    deps: [start:client, start:supabase]
  start:client:
    dir: packages/client
    cmds:
      - pnpm start

  test:
    deps: [test:client]
  test:client:
    dir: packages/client
    cmds:
      - pnpm test

  reset-db:
    dir: packages/supabase
    cmds:
      - pnpm reset

  lint:
    deps: [lint:client]
  lint:client:
    dir: packages/client
    cmds:
      - pnpm lint

  destroy:
    deps: [destroy:client]
  destroy:client:
    dir: packages/client
    cmds:
      - pnpm sst:remove

  destroy:prod:
    deps: [destroy:prod:client]
  destroy:prod:client:
    dir: packages/client
    cmds:
      - pnpm sst:remove:prod

  deploy:
    deps: [deploy:client]
  deploy:client:
    dir: packages/client
    cmds:
      - pnpm sst:deploy

  clean:
    deps: [clean:client]
  clean:client:
    dir: packages/client
    cmds:
      - pnpm clean

  stop:
    dir: packages/supabase
    cmds:
      - pnpm stop

  encrypt:
    deps: [encrypt:client, encrypt:supabase]
  encrypt:client:
    dir: packages/client
    cmds:
      - pnpm encrypt
  encrypt:supabase:
    dir: packages/supabase
    cmds:
      - pnpm encrypt

  decrypt:
    deps: [decrypt:client, decrypt:supabase]
  decrypt:client:
    dir: packages/client
    cmds:
      - pnpm decrypt
  decrypt:supabase:
    dir: packages/supabase
    cmds:
      - pnpm decrypt

  trace:
    deps: [trace:client]
  trace:client:
    dir: packages/client
    cmds:
      - pnpm trace

  typecheck:
    deps: [typecheck:client]
  typecheck:client:
    dir: packages/client
    cmds:
      - pnpm typecheck

  check:
    cmds:
      - pnpm check

