version: '3'

tasks:
  dev:
    deps: [dev:client, dev:supabase]
  dev:client:
    dir: packages/client
    cmds:
      - pnpm dev:remix
      - pnpm dev:css
  dev:supabase:
    dir: packages/supabase
    status:
      - pnpm status
    cmds:
      - pnpm start

  build:
    deps: [build:client]
  build:client:
    dir: packages/client
    cmds:
      - pnpm build

  test:
    deps: [test:client]
  test:client:
    dir: packages/client
    cmds:
      - pnpm test

  deploy:
    deps: [deploy:client]
  deploy:client:
    dir: packages/client
    cmds:
      - pnpm run deploy

  clean:
    deps: [clean:client]
  clean:client:
    dir: packages/client
    cmds:
      - pnpm clean

  stop:
    dir: packages/supabase
    cmds:
      - pnpm stop

  encrypt:
    deps: [encrypt:client, encrypt:supabase]
  encrypt:client:
    dir: packages/client
    cmds:
      - pnpm encrypt
  encrypt:supabase:
    dir: packages/supabase
    cmds:
      - pnpm encrypt

  decrypt:
    deps: [decrypt:client, decrypt:supabase]
  decrypt:client:
    dir: packages/client
    cmds:
      - pnpm decrypt
  decrypt:supabase:
    dir: packages/supabase
    cmds:
      - pnpm decrypt
