[build.environment]
  NPM_FLAGS = "--version"

[build]
  command = "pnpm i --no-frozen-lockfile && pnpm build:css && pnpm build:remix"
  publish = "public"

[dev]
  command = "pnpm watch"
  port = 2000

[context.dev.environment]
  NODE_ENV = "development"
  REMIX_ENV = "development"

# [[redirects]]
#   from = "/api/users/login"
#   to = "/.netlify/functions/login"
#   status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[functions]
  node_bundler = "esbuild"

### disabling seed function
# [[edge_functions]]
#   path = "/api/users/seed-admin-user"
#   function = "seedAdminUser"

### disabling until edge functions support the deno unstable flag on production
# [[edge_functions]]
#   path = "/api/users/login"
#   function = "loginPlanetscale"

### had to rename the netlify folder to netlify.old to prevent error on local dev when not using the functions