-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE public.user_roles
    ALTER COLUMN id TYPE integer;
ALTER TABLE IF EXISTS public.user_roles
    ALTER COLUMN id SET INCREMENT 1 RESTART SET START 1 SET MINVALUE 1 SET MAXVALUE 2147483647 SET CACHE 1;
