name: Build

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Unit Test
        run: bun run test
